version: '3.8'

services:
  competitionscell:
    build:
      context: ./CompetitionsCell/CompetitionsCell
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DOTNET_RUNNING_IN_CONTAINER=true

  notificationscell:
    build:
      context: ./NotificationsCell/NotificationsCell
      dockerfile: Dockerfile
    ports:
      - "5005:5005"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DOTNET_RUNNING_IN_CONTAINER=true

  paymentscell:
    build:
      context: ./PaymentsCell/PaymentsCell
      dockerfile: Dockerfile
    ports:
      - "5002:5002"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DOTNET_RUNNING_IN_CONTAINER=true

  trainingscell:
    build:
      context: ./TrainingsCell/TrainingsCell
      dockerfile: Dockerfile
    ports:
      - "5003:5003"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DOTNET_RUNNING_IN_CONTAINER=true

  userscell:
    build:
      context: ./UsersCell/UsersCell
      dockerfile: Dockerfile
    ports:
      - "5004:5004"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DOTNET_RUNNING_IN_CONTAINER=true

  mediacell:
    build:
      context: ./MediaCell/MediaCell
      dockerfile: Dockerfile
    ports:
      - "5006:5006"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DOTNET_RUNNING_IN_CONTAINER=true
  apigateway:
    build:
      context: ./APIGateway/APIGateway
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DOTNET_RUNNING_IN_CONTAINER=true
