version: '3.8'

services:
  competitionscell:
    build:
      context: ./CompetitionsCell/CompetitionsCell
      dockerfile: Dockerfile
    ports:
      - "7001:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DOTNET_RUNNING_IN_CONTAINER=true

  notificationscell:
    build:
      context: ./NotificationsCell/NotificationsCell
      dockerfile: Dockerfile
    ports:
      - "7005:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DOTNET_RUNNING_IN_CONTAINER=true

  paymentscell:
    build:
      context: ./PaymentsCell/PaymentsCell
      dockerfile: Dockerfile
    ports:
      - "7002:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DOTNET_RUNNING_IN_CONTAINER=true

  trainingscell:
    build:
      context: ./TrainingsCell/TrainingsCell
      dockerfile: Dockerfile
    ports:
      - "7003:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DOTNET_RUNNING_IN_CONTAINER=true

  userscell:
    build:
      context: ./UsersCell/UsersCell
      dockerfile: Dockerfile
    ports:
      - "7004:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DOTNET_RUNNING_IN_CONTAINER=true
