/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as UsersImport } from './routes/users'
import { Route as TrainingsImport } from './routes/trainings'
import { Route as LoginImport } from './routes/login'
import { Route as CalendarImport } from './routes/calendar'
import { Route as IndexImport } from './routes/index'
import { Route as CompetitionsIndexImport } from './routes/competitions/index'
import { Route as CompetitionsIdImport } from './routes/competitions/$id'

// Create/Update Routes

const UsersRoute = UsersImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRoute,
} as any)

const TrainingsRoute = TrainingsImport.update({
  id: '/trainings',
  path: '/trainings',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const CalendarRoute = CalendarImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const CompetitionsIndexRoute = CompetitionsIndexImport.update({
  id: '/competitions/',
  path: '/competitions/',
  getParentRoute: () => rootRoute,
} as any)

const CompetitionsIdRoute = CompetitionsIdImport.update({
  id: '/competitions/$id',
  path: '/competitions/$id',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/trainings': {
      id: '/trainings'
      path: '/trainings'
      fullPath: '/trainings'
      preLoaderRoute: typeof TrainingsImport
      parentRoute: typeof rootRoute
    }
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersImport
      parentRoute: typeof rootRoute
    }
    '/competitions/$id': {
      id: '/competitions/$id'
      path: '/competitions/$id'
      fullPath: '/competitions/$id'
      preLoaderRoute: typeof CompetitionsIdImport
      parentRoute: typeof rootRoute
    }
    '/competitions/': {
      id: '/competitions/'
      path: '/competitions'
      fullPath: '/competitions'
      preLoaderRoute: typeof CompetitionsIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/login': typeof LoginRoute
  '/trainings': typeof TrainingsRoute
  '/users': typeof UsersRoute
  '/competitions/$id': typeof CompetitionsIdRoute
  '/competitions': typeof CompetitionsIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/login': typeof LoginRoute
  '/trainings': typeof TrainingsRoute
  '/users': typeof UsersRoute
  '/competitions/$id': typeof CompetitionsIdRoute
  '/competitions': typeof CompetitionsIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/login': typeof LoginRoute
  '/trainings': typeof TrainingsRoute
  '/users': typeof UsersRoute
  '/competitions/$id': typeof CompetitionsIdRoute
  '/competitions/': typeof CompetitionsIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/calendar'
    | '/login'
    | '/trainings'
    | '/users'
    | '/competitions/$id'
    | '/competitions'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calendar'
    | '/login'
    | '/trainings'
    | '/users'
    | '/competitions/$id'
    | '/competitions'
  id:
    | '__root__'
    | '/'
    | '/calendar'
    | '/login'
    | '/trainings'
    | '/users'
    | '/competitions/$id'
    | '/competitions/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalendarRoute: typeof CalendarRoute
  LoginRoute: typeof LoginRoute
  TrainingsRoute: typeof TrainingsRoute
  UsersRoute: typeof UsersRoute
  CompetitionsIdRoute: typeof CompetitionsIdRoute
  CompetitionsIndexRoute: typeof CompetitionsIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalendarRoute: CalendarRoute,
  LoginRoute: LoginRoute,
  TrainingsRoute: TrainingsRoute,
  UsersRoute: UsersRoute,
  CompetitionsIdRoute: CompetitionsIdRoute,
  CompetitionsIndexRoute: CompetitionsIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/calendar",
        "/login",
        "/trainings",
        "/users",
        "/competitions/$id",
        "/competitions/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/calendar": {
      "filePath": "calendar.tsx"
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/trainings": {
      "filePath": "trainings.tsx"
    },
    "/users": {
      "filePath": "users.tsx"
    },
    "/competitions/$id": {
      "filePath": "competitions/$id.tsx"
    },
    "/competitions/": {
      "filePath": "competitions/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
